// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeikavw-dBr2RScKZc5gITekIk4jEjpXM',
    appId: '1:64927244395:web:f5f13cc8b249b45ecd912e',
    messagingSenderId: '64927244395',
    projectId: 'student-1f588',
    authDomain: 'student-1f588.firebaseapp.com',
    databaseURL: 'https://student-1f588-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-1f588.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDilErJo1Mdnjdc685HjQ6D2x_WdECKLFg',
    appId: '1:64927244395:android:06c616dae0863b46cd912e',
    messagingSenderId: '64927244395',
    projectId: 'student-1f588',
    databaseURL: 'https://student-1f588-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-1f588.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt3qFQX8CBULXK2v1s_qYZl6hFwH80tpk',
    appId: '1:64927244395:ios:a468c6891961e322cd912e',
    messagingSenderId: '64927244395',
    projectId: 'student-1f588',
    databaseURL: 'https://student-1f588-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-1f588.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt3qFQX8CBULXK2v1s_qYZl6hFwH80tpk',
    appId: '1:64927244395:ios:a468c6891961e322cd912e',
    messagingSenderId: '64927244395',
    projectId: 'student-1f588',
    databaseURL: 'https://student-1f588-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-1f588.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeikavw-dBr2RScKZc5gITekIk4jEjpXM',
    appId: '1:64927244395:web:58dabe7c0d466f2bcd912e',
    messagingSenderId: '64927244395',
    projectId: 'student-1f588',
    authDomain: 'student-1f588.firebaseapp.com',
    databaseURL: 'https://student-1f588-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-1f588.firebasestorage.app',
  );
}
